### ISSUE TITLE
Target directory /Users/henkvancann/repos already exists. Exiting...

### ISSUE THREAD

**Issue by henkvancann** [trustoverip/spec-up-t-old#10]
repos ➤ npx create-spec-up-t-starterpack    
                                                                                                               
Target directory /Users/henkvancann/repos already exists. Exiting...

because spec-up-t-starterpack no longer exists in repos as dir and yet your script starts "wining" :)

 but target dir is not 'repos' but I am in 'repos' and want to create 'spec-up-t-starterpack' dir there

Again target dir is not 'repos' but I am in 'repos' and want to create 'spec-up-t-starterpack' dir there

Kor:
it also has to be different
the argument, targetDir, see picture, should not be used at all
![image](https://github.com/blockchainbird/spec-up-t/assets/479356/ccafe48c-a918-45e4-a4f4-b1fe30067d85)

**Comment by kordwarshuis** [comment]
This code served no purpose. Now checking for the right things, and also made configurable
