### ISSUE TITLE
Edit button functionality takes the last one from definition list, should be the first

### ISSUE THREAD

**Issue by henkvancann** [trustoverip/spec-up-t-old#11]
Funny, I discover a bug -> 'action' term Edit button -> acts.md and therefore a 404
oops, but also actor -> actors.md 404

It seems like the Edit button functionality takes the last one from [[def: actor, actors]] and not the first one (which represents the {file name}.md

https://github.com/trustoverip/ctwg-main-glossary/blob/main/spec/terms-definitions/agents.md suspicion confirmed?
https://github.com/trustoverip/ctwg-main-glossary/blob/main/spec/terms-definitions/scopes.md also

**Comment by kordwarshuis** [comment]
Nested <span>'s made selection go wrong. Now the deepest <span> is selected.
Anchors had the same bug, this is also fixed.
