### ISSUE TITLE
Decide if directories belong in the repo or not

### ISSUE THREAD

**Issue by kordwarshuis** [trustoverip/spec-up-t-old#21]
Decide if these directories belong in the repo or not:

`/docs`
`/multi-file-test`
`/single-file-test`

Since we have the installer (`npx create-spec-up-t`), what is the use of these directories?

`/docs` --> .gitignore ?
`/multi-file-test`--> delete ?
`/single-file-test`--> delete ?

**Comment by henkvancann** [comment]
Interesting to see the difference between:
1. https://github.com/decentralized-identity/spec-up/tree/master/multi-file-test, where the usual .md files are present as a source and 
2. https://github.com/decentralized-identity/spec-up/tree/master/single-file-test where one spec.md file is used with some `asset`-subdir 

In the single file test, Daniel "pulls in" the json and the test.text data with this _code in spec.md_, or at least he tries (see bold):

"
Use the following format to pull in content from other files in your project:

<pre>
This text has been inserted here from another file: &#91;&#91;insert: ./single-file-test/assets/test.text&#93;&#93;
</pre>

**This text has been inserted here from another file: [[insert: ./single-file-test/assets/test.text]]**

You can even insert content within more complex blocks, like the JSON object below which is being pulled in and rendered in a syntax-highlighted example block:

<pre>
::: example Code Example
```json
&#91;&#91;insert: ./single-file-test/assets/test.json&#93;&#93;
```
:::
</pre>

::: example Code Example
```json
[[insert: ./single-file-test/assets/test.json]]
```
:::
"

The result [here](https://github.com/decentralized-identity/spec-up/blob/master/single-file-test/spec.md#content-insertion), however, doesn't show the text "Beam, me over, Scotty"

To get back to the question 'What to do with Single/Multi file test?' I would say: get rid of it for the time being.

**Comment by kordwarshuis** [comment]
Agreed!

It seems to me that two options in Spec-Up are not being used anymore:
- Single file
- Multiple specs (notice that `specs` (in `specs.json`) is an array)

**Comment by kordwarshuis** [comment]
Created branch `archive/before-deleting-file-test-dirs` (https://github.com/blockchainbird/spec-up-t/tree/archive/before-deleting-file-test-dirs) and deleted these dirs:

`/multi-file-test`
`/single-file-test`

The default output dir for the `index.html` file, `/docs`, is added to .gitignore since it serves no purpose in the spec-up-t package itself.
