### ISSUE TITLE
Blank line assurance wanted

### ISSUE THREAD

**Issue by henkvancann** [trustoverip/spec-up-t-old#6]
The individual term files are vulnerable: if the last line of the previous term file does not have a hard return, the merge breaks.

See the blue highlight:

![Screenshot 2024-06-16 at 21 34 08](https://github.com/blockchainbird/spec-up-t/assets/479356/ed75474a-9786-4337-836f-63709c7790a3)

This is after repair in internet-scale-digital-trust.md: added a hard return
![Screenshot 2024-06-16 at 21 34 33](https://github.com/blockchainbird/spec-up-t/assets/479356/9ceaa4ac-4999-4093-bf1f-446a1a9b9732)

Kor:
In my fix script I already have a blank line after the term blank line
There will also have to be a blank line after the definition

**Comment by kordwarshuis** [comment]
The before mentioned fix script is part of https://github.com/blockchainbird/spec-up-splitter

This repo should get it's own fix script.

**Comment by kordwarshuis** [comment]
- Script created
- Runs via render command
- Published on NPM
