### ISSUE TITLE
“Diff” button not working (to be closed with tag name 1.0.3)

### ISSUE THREAD

**Issue by henkvancann** [trustoverip/spec-up-t-old#7]
Diff button compares a commit# with a filename.
Needs to be 2 commit-hashes.

**Comment by henkvancann** [comment]
first [13](https://github.com/blockchainbird/spec-up-t/issues/13)

**Comment by kordwarshuis** [comment]
Update:
Kor: I have closed https://github.com/blockchainbird/spec-up-t/issues/13

**Comment by henkvancann** [comment]
tag names are to be discussed more in the future
